version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /app/ulc:/app/ulc
  memcached:
    image: memcached:latest
  db:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
       MYSQL_ROOT_PASSWORD: ulc123
       MYSQL_DATABASE: ulcdocker
       MYSQL_USER: ulc
       MYSQL_PASSWORD: ulc
