FROM mysql:latest
ENV MYSQL_ROOT_PASSWORD="ulc123"
ENV MYSQL_DATABASE="ulcdocker"
ENV MYSQL_USER="ulc"
ENV MYSQL_PASSWORD="ulc"
EXPOSE 3306
CMD ["mysqld", "--character-set-server=utf8", "--collation-server=utf8_general_ci"]


